# Generated by Django 2.2.5 on 2019-11-01 18:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='area',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='pop2005',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='region',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='un',
        ),
        migrations.AddField(
            model_name='worldborder',
            name='address',
            field=models.CharField(default='Heya', max_length=100),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='city',
            field=models.CharField(default='Howye', max_length=50),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='Story', srid=4326),
        ),
    ]
